name: spoten_packages
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/spoten/spoten_diverses_packages

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  uuid: ^4.5.1
  meta: ^1.15.0
  archive: ^3.3.8
  cli_script: ^1.0.0
  crypto: ^3.0.6
  equatable: ^2.0.7
  path: ^1.9.0
  path_provider: ^2.1.5
  js: ^0.7.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: net.touchcapture.qr.flutterqr
        pluginClass: FlutterQrPlugin
      ios:
        pluginClass: FlutterQrPlugin

